CREATE TABLE GCG_3960_BI_LBR_DTL(
 BIRUNID INTEGER,
 JOBSUFFIX Char(10),
 SEQ CHAR(6),
 EMP_WC CHAR(5),
 CHARGE_DATE DATE,
 HOURS_WORKED NUMERIC(12,4),
 AMT_LABOR NUMERIC(10,2),
 AMT_OVERHEAD NUMERIC(10,2));